version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          FLASK_ENV: testing
          DB_TESTING: postgresql://postgres@localhost/scm_test_db
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: scm_test_db
          POSTGRES_PASSWORD:

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --statistics --exclude=venv*,alembic
            coverage run --source=tests -m pytest && coverage report
