"""Add a user type column to user table

Revision ID: 5635ec9d572f
Revises: 7a1b58892f4d
Create Date: 2019-08-28 13:00:54.199145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5635ec9d572f'
down_revision = '7a1b58892f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_type = postgresql.ENUM(
        'default', 'admin', 'super_admin', name='usertype')
    user_type.create(op.get_bind())
    op.add_column('users', sa.Column('user_type', sa.Enum('default', 'admin', 'super_admin', name='usertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
