"""Add a products table and relationship with user

Revision ID: 8e2140b92427
Revises: 5635ec9d572f
Create Date: 2019-10-02 11:51:07.397671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e2140b92427'
down_revision = '5635ec9d572f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('manufacturer', postgresql.ENUM('none', name='manufacturer'), nullable=True),
    sa.Column('UOM', postgresql.ENUM('none', 'tonnes', 'litre', 'kilogram', 'metre', name='uom'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
